INSERT INTO Servizio (Descrizione, Prezzo) VALUES ('Servizio in camera', 20.00);
INSERT INTO Servizio (Descrizione, Prezzo) VALUES ('Accesso alla spa', 50.00);
INSERT INTO Servizio (Descrizione, Prezzo) VALUES ('Parcheggio privato', 10.00);
INSERT INTO Servizio (Descrizione, Prezzo) VALUES ('Colazione in camera', 15.00);
INSERT INTO Servizio (Descrizione, Prezzo) VALUES ('Lavanderia', 10.00);
INSERT INTO Servizio (Descrizione, Prezzo) VALUES ('Noleggio biciclette', 25.00);
INSERT INTO Servizio (Descrizione, Prezzo) VALUES ('Abbonamento palestra', 30.00);
INSERT INTO Servizio (Descrizione, Prezzo) VALUES ('Wi-Fi ad alta velocità', 5.00);
INSERT INTO Servizio (Descrizione, Prezzo) VALUES ('Trasferimento aeroportuale', 40.00);
INSERT INTO Servizio (Descrizione, Prezzo) VALUES ('Servizio di babysitting', 60.00);